In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

Load Data

In [26]:
sales = pd.read_json("../data/Sales.json")
forecast = pd.read_json("../data/Forecast.json")

Data Structure

In [27]:
print("Sales Shape:", sales.shape)
print("Forecast Shape:", forecast.shape)

Sales Shape: (298246, 18)
Forecast Shape: (33, 4)

In [28]:
sales.head()

,ProductKey,Product Name,Brand,Color,Subcategory,Category,CustomerKey,Customer Code,Name,Education,Occupation,Continent,City,State,CountryRegion,OrderDate,Quantity,Net Price
0,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,NaN,NaN,NaN,North America,Spokane,Washington,United States,1/1/2008,1,23.7405
1,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,NaN,NaN,NaN,North America,Spokane,Washington,United States,1/1/2008,1,23.7405
2,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,NaN,NaN,NaN,North America,Spokane,Washington,United States,1/1/2008,1,23.7405
3,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,NaN,NaN,NaN,North America,Spokane,Washington,United States,1/1/2008,1,23.7405
4,2492,Cigarette Lighter Adapter for Contoso Phones E...,Contoso,Cell phones Accessories,Cell phones Accessories,Cell phones,18813,CS551,NaN,NaN,NaN,North America,Spokane,Washington,United States,1/1/2008,1,23.7405

In [29]:
forecast.head()

  CountryRegion            Brand  Forecast  Year
0         China         A. Datum    201487  2009
1         China  Adventure Works    399490  2009
2         China          Contoso   1173308  2009
3         China         Fabrikam    790074  2009
4         China          Litware    437443  2009

In [30]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 298246 entries, 0 to 298245
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ProductKey     298246 non-null  int64
 1   Product Name   298246 non-null  str
 2   Brand          298246 non-null  str
 3   Color          298246 non-null  str
 4   Subcategory    298246 non-null  str
 5   Category       298246 non-null  str
 6   CustomerKey    298246 non-null  int64
 7   Customer Code  298246 non-null  str
 8   Name           29797 non-null   str
 9   Education      29797 non-null   str
 10  Occupation     29797 non-null   str
 11  Continent      298246 non-null  str
 12  City           298246 non-null  str
 13  State          298246 non-null  str
 14  CountryRegion  298246 non-null  str
 15  OrderDate      298246 non-null  str
 16  Quantity       298246 non-null  int64
 17  Net Price      298246 non-null  float64
dtypes: float64(1), int64(3), str(14)
memory usage: 41.0 MB

In [31]:
forecast.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryRegion  33 non-null     str
 1   Brand          33 non-null     str
 2   Forecast       33 non-null     int64
 3   Year           33 non-null     int64
dtypes: int64(2), str(2)
memory usage: 1.2 KB

Missing Values

In [32]:
sales.isnull().sum().sort_values(ascending=False)

Education        268449
Name             268449
Occupation       268449
ProductKey            0
Product Name          0
Brand                 0
Category              0
Subcategory           0
Customer Code         0
Color                 0
CustomerKey           0
Continent             0
City                  0
State                 0
CountryRegion         0
OrderDate             0
Quantity              0
Net Price             0
dtype: int64

In [33]:
forecast.isnull().sum()

CountryRegion    0
Brand            0
Forecast         0
Year             0
dtype: int64

Check Duplicates

In [34]:
print(sales.duplicated().sum())

218008

In [35]:
print(forecast.duplicated().sum())

0

Dates Analysis

In [36]:
sales["OrderDate"] = pd.to_datetime(
    sales["OrderDate"]
)

In [43]:
sales["OrderDate"].min()

Timestamp('2008-01-01 00:00:00')

In [44]:
sales["OrderDate"].max()

Timestamp('2009-12-31 00:00:00')

In [45]:
sales["OrderDate"].dt.year.value_counts()

OrderDate
2009    167372
2008    130874
Name: count, dtype: int64

Create Sales Amount

In [ ]:
# SalesAmount = Quantity * Net Price 
sales["SalesAmount"] = (
    sales["Quantity"] *
    sales["Net Price"]
)

In [47]:
sales["SalesAmount"].describe()

count    298246.000000
mean        280.087920
std         572.941516
min           0.760000
25%          18.976000
50%          98.955000
75%         297.000000
max       12799.960000
Name: SalesAmount, dtype: float64

Product Analysis

In [48]:
sales["ProductKey"].nunique()

2495

In [49]:
sales["Brand"].nunique()

11

In [50]:
sales.groupby(
    "Brand"
)["SalesAmount"].sum().sort_values(
    ascending=False
)

Brand
Contoso                 1.870981e+07
Fabrikam                1.591857e+07
Litware                 1.061045e+07
Adventure Works         9.400695e+06
Proseware               7.594486e+06
Wide World Importers    6.646252e+06
The Phone Company       3.865383e+06
A. Datum                3.695572e+06
Southridge Video        3.464651e+06
Northwind Traders       2.613372e+06
Tailspin Toys           1.015868e+06
Name: SalesAmount, dtype: float64

Customer Analysis

In [51]:
sales["CustomerKey"].nunique()

8868

In [52]:
sales.groupby(
    "CustomerKey"
)["SalesAmount"].sum().sort_values(
    ascending=False
).head(10)

CustomerKey
19056    2.240350e+06
19049    2.006752e+06
19057    1.767642e+06
19066    1.718787e+06
19053    1.650413e+06
19120    1.176044e+06
19075    1.088309e+06
19125    9.736448e+05
19137    8.963781e+05
19126    8.474596e+05
Name: SalesAmount, dtype: float64

Forecast Analysis

In [53]:
forecast.head()

  CountryRegion            Brand  Forecast  Year
0         China         A. Datum    201487  2009
1         China  Adventure Works    399490  2009
2         China          Contoso   1173308  2009
3         China         Fabrikam    790074  2009
4         China          Litware    437443  2009

In [54]:
forecast["CountryRegion"].nunique()

3

In [55]:
forecast["Brand"].nunique()

11

In [58]:
print(forecast["Year"].unique())

[2009]

In [59]:
print(forecast.groupby(
    ["CountryRegion", "Brand", "Year"]
).size())

CountryRegion  Brand                 Year
China          A. Datum              2009    1
               Adventure Works       2009    1
               Contoso               2009    1
               Fabrikam              2009    1
               Litware               2009    1
               Northwind Traders     2009    1
               Proseware             2009    1
               Southridge Video      2009    1
               Tailspin Toys         2009    1
               The Phone Company     2009    1
               Wide World Importers  2009    1
Germany        A. Datum              2009    1
               Adventure Works       2009    1
               Contoso               2009    1
               Fabrikam              2009    1
               Litware               2009    1
               Northwind Traders     2009    1
               Proseware             2009    1
               Southridge Video      2009    1
               Tailspin Toys         2009    1
               The Phone Company     2009    1
               Wide World Importers  2009    1
United States  A. Datum              2009    1
               Adventure Works       2009    1
               Contoso               2009    1
               Fabrikam              2009    1
               Litware               2009    1
               Northwind Traders     2009    1
               Proseware             2009    1
               Southridge Video      2009    1
               Tailspin Toys         2009    1
               The Phone Company     2009    1
               Wide World Importers  2009    1
dtype: int64

Sales Granularity

In [60]:
sales[
    [
        "ProductKey",
        "CustomerKey",
        "OrderDate",
        "Quantity",
        "Net Price"
    ]
].head()

   ProductKey  CustomerKey  OrderDate  Quantity  Net Price
0        2492        18813 2008-01-01         1    23.7405
1        2492        18813 2008-01-01         1    23.7405
2        2492        18813 2008-01-01         1    23.7405
3        2492        18813 2008-01-01         1    23.7405
4        2492        18813 2008-01-01         1    23.7405